export const ACTIONS = {
  GET_LISTINGS: "GET_LISTINGS",
  LOADING: "LOADING",
  DOWNLOAD_MODAL: "DOWNLOAD_MODAL",
  NEWS_MODAL: "NEWS_MODAL",
  CONTACT_MODAL: "CONTACT_MODAL",
  ALL_LISTINGS: "ALL_LISTINGS",
  CHECKLOAD: "CHECKLOAD",
  CALLBACK: "CALLBACK",
};
